### ISSUE TITLE
esp32 sqlite insert varible in table

### ISSUE THREAD

**Issue by reshma26994** [siara-cc/sqlite_micro_logger_arduino#6]
rc = db_exec(db1, "INSERT INTO test1 VALUES (1,1);");
by this  insert 1(hardcoded) in column in table but,
int i=4;
how to insert variable i in table

**Comment by reshma26994** [comment]
please give response

**Comment by justinclift** [comment]
It will **_probably_** depend on whatever programming language you are using for communication to the esp32.

To embed variables in the string, it's **_probably_** going to be the SQLite placeholder character, which is generally the question mark (`?'):

&nbsp; &nbsp; https://sqlite.org/lang_expr.html#parameters

Note that I'm saying "probably" because I don't personally use this library, so am just guessing based on standard SQLite things.

As a side note, GitHub is **not** the place you should be asking questions when you need a fast response.  It's more like email, where you ask a question and hope to get a response by the next day most of the time. :wink:

You might get lucky though.  And you could ask on the SQLite Users Forum too:

&nbsp; &nbsp; https://sqlite.org/forum/forum

**Comment by reshma26994** [comment]
please give me proper example(syntax) to insert variable in table currently refering example of sqlite spiffs ..i am using esp32 on arduino IDE

**Comment by siara-cc** [comment]
@justinclift Hi, I appreciate your answer.  I never saw this issue because I was not a watcher at that time.

**Comment by justinclift** [comment]
@siara-cc No worries at all. :smile:
